### PR TITLE
fix(localbrick): fails if the folder brick is removed

### LINKED ISSUE #353: local brick: do not fail if the local brick present into the app.yaml is not found in the folders
## Motivation
If the brick folder is deleted from the bricks, the list of bricks of the app fails with tthis error:

```
ERROR Unable to parse the app.yaml error="brick not found with id pluto"
```

### PR DESCRIPTION
**Pull request by dido18**
### Motivation

If the folder of a local brick is removed using the file manager, the following errors occur.
 - the `GET /v1/apps/{appID}/bricks` fails with the error `error="brick not found with id pluto"`
 - the  `DELETE /v1/apps/{appID}/bricks/{brickID}"` fails beacsue the brick is not found 

### Change description
- the get bricks returns the brick id with a status "not found" instead of an error
```
{
  "bricks": [
    {

      "id": "test4",
      "name": "test4",
      "author": "",
      "category": "",
      "status": "not found",
      "require_model": false,
      "compatible_models": null,
      "readme": ""
    }
]
```

- The delete endpoint returns not found only if the brick ID is not found in the `app.yaml` 

### Reviewer checklist

- [ ] PR addresses a single concern.
- [ ] PR title and description are properly filled.
- [ ] Changes will be merged in `main`.
- [ ] Changes are covered by tests.
- [ ] Logging is meaningful in case of troubleshooting.

### CODE REVIEW

File: internal/orchestrator/bricks/bricks.go [hunk 1]
```diff
@@ -439,7 +444,7 @@ func (s *Service) BrickDelete(
 	appCurrent *app.ArduinoApp,
 	id string,
 ) error {
-	if _, present := s.bricksIndex.WithAppBricks(appCurrent.LocalBricks).FindBrickByID(id); !present {
+	if slices.IndexFunc(appCurrent.Descriptor.Bricks, func(b app.Brick) bool { return b.ID == id }) == -1 {
```
Comment (lucarin91) [inline internal/orchestrator/bricks/bricks.go]:
```suggestion
	if !slices.ContainFunc(appCurrent.Descriptor.Bricks, func(b app.Brick) bool { return b.ID == id }) {
```

**Review by lucarin91 — APPROVED** [review]
