### PR TITLE
fix: update reconnection flow (mutex)

### LINKED ISSUE #381: Inconsistent "ErrOperationAlreadyInProgress" when checking for updates
When checking for updates (ListUpgradablePackages) a specific error is returned if an operation is already in progress. The code returns this error both if there is already an upgrade in progress and if there is a check in progress.

This is causing a infinite update in the App Lab because it will try to do a check for updates first, and see if an upgrade is in progress. In that case it will then connect to the events endpoint. But if there are multiple check for updates pending, the specific return code is given anyway, and App Lab will wrongly think there is an update in progress (while there is just a check for updates). In this case, opening the events not only is useless but it will lock there forever, because it will never return a "upgrade finished" event.

The specific return status should only be returned if an upgrade in progress, multiple checks are fine (and are serialized anyway with a lock in the underlying service).

See also: https://github.com/arduino/arduino-app-cli/issues/382

### PR DESCRIPTION
**Pull request by lucarin91**
### Motivation

The system update has a set of inconsistencies that make the reconnection to an ongoing update buggy.

First of all, the `update/check` operation shouldn't lock the upgrade operation; multiple parties could call the check without getting an `OPERATION_IN_PROGRESS`. Indeed, this error means that an `update/apply` is in progress not a check. The upgrade operation is the real locking operation that should return an error in case another upgrade operation is in progress.

~Second, the `system/events` stream should immediately return if there isn't any upgrade operation in progress, which will prevent having a stale SSE event that never returns.~

### Change description

1. Remove the global lock and use instead an atomic, which allows to check the status of the upgrade without changing it
2. Make only the manager returning the `OPERATION_IN_PROGRESS` the two update services, only use a global lock.
~3. Substribe method returns a closed channel if no events will ever arrive~

### Reviewer checklist

- [ ] PR addresses a single concern.
- [ ] PR title and description are properly filled.
- [ ] Changes will be merged in `main`.
- [ ] Changes are covered by tests.
- [ ] Logging is meaningful in case of troubleshooting.

### CODE REVIEW

File: internal/update/update.go [hunk 1]
```diff
@@ -74,10 +75,12 @@ func NewManager(debUpdateService ServiceUpdater, arduinoPlatformUpdateService Se
 }
 
 func (m *Manager) ListUpgradablePackages(ctx context.Context, matcher func(UpgradablePackage) bool) ([]UpgradablePackage, error) {
-	if !m.lock.TryLock() {
+	m.isUgradingMutex.RLock()
+	if m.isUpgrading {
+		defer m.isUgradingMutex.RUnlock()
```
Comment (Xayton) [inline internal/update/update.go]: The defer on this line is probably redundant.

File: internal/update/update.go [hunk 2]
```diff
@@ -57,7 +57,8 @@ type ServiceUpdater interface {
 }
 
 type Manager struct {
-	lock                         sync.Mutex
+	isUgradingMutex              sync.RWMutex
```
Comment (Xayton) [inline internal/update/update.go]:
```suggestion
	isUpgradingMutex              sync.RWMutex
```

File: internal/update/update.go [hunk 3]
```diff
@@ -74,10 +75,12 @@ func NewManager(debUpdateService ServiceUpdater, arduinoPlatformUpdateService Se
 }
 
 func (m *Manager) ListUpgradablePackages(ctx context.Context, matcher func(UpgradablePackage) bool) ([]UpgradablePackage, error) {
-	if !m.lock.TryLock() {
+	m.isUgradingMutex.RLock()
```
Comment (Xayton) [inline internal/update/update.go]:
```suggestion
	// If an upgrade is in progress, return a specific error so that the App Lab knows and can open the 
	// events stream. This is returned only if an upgrade is in progress, not if another check for updates
	// is running (which is acceptable).
	m.isUgradingMutex.RLock()
```

File: internal/update/update.go [hunk 4]
```diff
@@ -74,10 +76,9 @@ func NewManager(debUpdateService ServiceUpdater, arduinoPlatformUpdateService Se
 }
 
 func (m *Manager) ListUpgradablePackages(ctx context.Context, matcher func(UpgradablePackage) bool) ([]UpgradablePackage, error) {
-	if !m.lock.TryLock() {
+	if m.isUpgrading.Load() {
```
Comment (Xayton) [inline internal/update/update.go:80]:
```suggestion
	// Atomically check if an upgrade operation is already in progress. See https://github.com/arduino/arduino-app-cli/issues/381.
	if m.isUpgrading.Load() {
```

**Review by Xayton — APPROVED** [review]
Tested and it works (I could not reproduce the issue anymore).
Updates still work.

**Comment by lucarin91** [comment]
The new tests highlight the following inconsistency in the upgrade events https://github.com/arduino/arduino-app-cli/issues/382
