### PR TITLE
fix: system init clean up with service

### LINKED ISSUE #366: system init/cleanup should download/remove services images
The system init command should also download all the Docker images in services and download them

https://github.com/arduino/arduino-app-cli/blob/90a0b4dee6c2f300e9adf0fcfa8384d289bc97e3/internal/orchestrator/system.go#L130

The system cleanup command should verify that old image of old services are correctly removed.

https://github.com/arduino/arduino-app-cli/blob/90a0b4dee6c2f300e9adf0fcfa8384d289bc97e3/internal/orchestrator/system.go#L269

### PR DESCRIPTION
**Pull request by lucarin91**
### Reviewer checklist

- [ ] PR addresses a single concern.
- [ ] PR title and description are properly filled.
- [ ] Changes will be merged in `main`.
- [ ] Changes are covered by tests.
- [ ] Logging is meaningful in case of troubleshooting.

### CODE REVIEW

**Review by MatteoPologruto — APPROVED** [review]

File: internal/orchestrator/system.go [hunk 1]
```diff
@@ -284,24 +278,24 @@ func getAllSupportedBrickImages(bricksIndex *bricksindex.BricksIndex) ([]string,
...
+			if !ok {
+				feedback.Warnf("brick %s requires service %s, but it was not found in the services index", brick.ID, serviceName)
+				continue
+			}
+			if serviceComposeFile, ok := service.GetComposeFile(); ok {
+				serviceImages, err := extractImagesFromCompose(serviceComposeFile)
+				if err != nil {
+					return nil, fmt.Errorf("failed to extract images from compose file of service %s required by brick %s: %w", serviceName, brick.ID, err)
+				}
+				images = append(images, serviceImages...)
```
Comment (mirkoCrobu) [inline internal/orchestrator/system.go:295]: are we missing a `result = append(result, images...)` here'? I mean, should we append service images to result?

Comment (MatteoPologruto) [reply internal/orchestrator/system.go:295]: I was checking this again and wondered the same thing. We should probably just do `result = append(result, serviceImages. . .)` because we don't want to include brick images twice.

Comment (lucarin91) [reply internal/orchestrator/system.go:295]: https://github.com/arduino/arduino-app-cli/pull/373
